# Generated by Django 6.0 on 2025-12-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skbank',
            name='svg',
            field=models.TextField(default='hd', max_length=50),
        ),
    ]
