# Generated by Django 6.0 on 2025-12-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnkapp', '0002_alter_skbank_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skbank',
            name='svg',
            field=models.TextField(blank=True, default='hd', max_length=50, null=True),
        ),
    ]
