# Generated by Django 6.0 on 2026-01-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnkapp', '0004_balancerequest_message_otplog_paymentdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=16),
        ),
    ]
