# Generated by Django 6.0 on 2026-01-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnkapp', '0006_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skbank',
            name='copyright',
            field=models.CharField(max_length=750),
        ),
    ]
