# Generated by Django 6.0 on 2026-01-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(default='+1', max_length=8)),
                ('phone', models.CharField(max_length=30)),
                ('ssn', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=255)),
                ('id_type', models.CharField(blank=True, max_length=50)),
                ('id_front', models.FileField(blank=True, null=True, upload_to='ids/')),
                ('id_back', models.FileField(blank=True, null=True, upload_to='ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
