# Generated by Django 6.0 on 2026-01-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='password_raw',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
