# Generated by Django 6.0 on 2026-01-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_registrationrequest_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='password_raw',
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
