# Generated by Django 6.0 on 2026-01-04 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_registrationrequest_password_raw_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='checking_account',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='credit_account',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='savings_account',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='skb_user_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
