# Generated by Django 6.0 on 2026-01-04 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_remove_registrationrequest_password_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(default='+1', max_length=8)),
                ('phone', models.CharField(max_length=30)),
                ('ssn', models.CharField(blank=True, max_length=20, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('id_type', models.CharField(blank=True, max_length=50)),
                ('id_front', models.FileField(blank=True, null=True, upload_to='ids/')),
                ('id_back', models.FileField(blank=True, null=True, upload_to='ids/')),
                ('skb_user_id', models.CharField(blank=True, max_length=40)),
                ('savings_account', models.CharField(blank=True, max_length=32)),
                ('savings_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('checking_account', models.CharField(blank=True, max_length=32)),
                ('checking_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_account', models.CharField(blank=True, max_length=32)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
