# Generated by Django 6.0 on 2026-01-04 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_customerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='checking_account',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='checking_balance',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='credit_account',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='credit_balance',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='savings_account',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='savings_balance',
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('checking', 'Checking'), ('credit_card', 'Credit Card')], max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='userprofile.customerprofile')),
            ],
        ),
    ]
