# Generated by Django 6.0 on 2026-01-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_recipient_payment_scheduledpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledpayment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
    ]
