# Generated by Django 6.0 on 2026-01-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_message_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='userstatus',
            field=models.BooleanField(default=True),
        ),
    ]
